#!/bin/sh
set -e
case "$1" in
	remove|upgrade|deconfigure)
		deb-systemd-helper stop battleship
	;;

	failed-upgrade)
		# the service would have already been stopped
		# earlier by the call to upgrade, no need to do
		# anything
	;;

	*)
		echo "unknown prerm argument \'$1\'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
